// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uHRmC1SQrkfdMqVjfGKf9u
// Component: OefAL3Aw-COiWL
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_blank_project_mobile_first_css from "../apoiase_website_mobile_first/plasmic_apoiase_website_mobile_first.module.css"; // plasmic-import: bFry1ML5XR1ujHJJdSKVcs/projectcss
import projectcss from "./plasmic_apoiase_home_mobile_first.module.css"; // plasmic-import: uHRmC1SQrkfdMqVjfGKf9u/projectcss
import sty from "./PlasmicNavButton.module.css"; // plasmic-import: OefAL3Aw-COiWL/css

import ApoiaseIconArrowDownIcon from "./icons/PlasmicIcon__ApoiaseIconArrowDown"; // plasmic-import: E5-wYW7gHkgxiY/icon

export type PlasmicNavButton__VariantMembers = {
  withStartIcon: "withStartIcon";
  withEndIcon: "withEndIcon";
  withSecondLevel: "withSecondLevel";
};

export type PlasmicNavButton__VariantsArgs = {
  withStartIcon?: SingleBooleanChoiceArg<"withStartIcon">;
  withEndIcon?: SingleBooleanChoiceArg<"withEndIcon">;
  withSecondLevel?: SingleBooleanChoiceArg<"withSecondLevel">;
};

type VariantPropType = keyof PlasmicNavButton__VariantsArgs;
export const PlasmicNavButton__VariantProps = new Array<VariantPropType>(
  "withStartIcon",
  "withEndIcon",
  "withSecondLevel"
);

export type PlasmicNavButton__ArgsType = {
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicNavButton__ArgsType;
export const PlasmicNavButton__ArgProps = new Array<ArgPropType>(
  "startIcon",
  "endIcon",
  "children"
);

export type PlasmicNavButton__OverridesType = {
  navButton?: p.Flex<"button">;
};

export interface DefaultNavButtonProps {
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  children?: React.ReactNode;
  withStartIcon?: SingleBooleanChoiceArg<"withStartIcon">;
  withEndIcon?: SingleBooleanChoiceArg<"withEndIcon">;
  withSecondLevel?: SingleBooleanChoiceArg<"withSecondLevel">;
  className?: string;
}

export const defaultNavButton__Args: Partial<PlasmicNavButton__ArgsType> = {};

function PlasmicNavButton__RenderFunc(props: {
  variants: PlasmicNavButton__VariantsArgs;
  args: PlasmicNavButton__ArgsType;
  overrides: PlasmicNavButton__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultNavButton__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <p.Stack
      as={"button"}
      data-plasmic-name={"navButton"}
      data-plasmic-override={overrides.navButton}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_blank_project_mobile_first_css.plasmic_tokens,
        sty.navButton,
        {
          [sty.navButtonwithEndIcon]: hasVariant(
            variants,
            "withEndIcon",
            "withEndIcon"
          ),
          [sty.navButtonwithStartIcon]: hasVariant(
            variants,
            "withStartIcon",
            "withStartIcon"
          )
        }
      )}
    >
      {(hasVariant(variants, "withStartIcon", "withStartIcon") ? true : false)
        ? p.renderPlasmicSlot({
            defaultContents: (
              <ApoiaseIconArrowDownIcon
                className={classNames(projectcss.all, sty.svg__z4TqJ)}
                role={"img"}
              />
            ),

            value: args.startIcon
          })
        : null}
      {p.renderPlasmicSlot({
        defaultContents: "Modalidades",
        value: args.children,
        className: classNames(sty.slotTargetChildren, {
          [sty.slotTargetChildrenwithEndIcon]: hasVariant(
            variants,
            "withEndIcon",
            "withEndIcon"
          ),
          [sty.slotTargetChildrenwithStartIcon]: hasVariant(
            variants,
            "withStartIcon",
            "withStartIcon"
          )
        })
      })}

      {(
        hasVariant(variants, "withEndIcon", "withEndIcon")
          ? true
          : hasVariant(variants, "withStartIcon", "withStartIcon")
          ? false
          : false
      )
        ? p.renderPlasmicSlot({
            defaultContents: (
              <ApoiaseIconArrowDownIcon
                className={classNames(projectcss.all, sty.svg__iVvnh)}
                role={"img"}
              />
            ),

            value: args.endIcon
          })
        : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  navButton: ["navButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  navButton: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavButton__VariantsArgs;
    args?: PlasmicNavButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNavButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavButton__ArgProps,
      internalVariantPropNames: PlasmicNavButton__VariantProps
    });

    return PlasmicNavButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "navButton") {
    func.displayName = "PlasmicNavButton";
  } else {
    func.displayName = `PlasmicNavButton.${nodeName}`;
  }
  return func;
}

export const PlasmicNavButton = Object.assign(
  // Top-level PlasmicNavButton renders the root element
  makeNodeComponent("navButton"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNavButton
    internalVariantProps: PlasmicNavButton__VariantProps,
    internalArgProps: PlasmicNavButton__ArgProps
  }
);

export default PlasmicNavButton;
/* prettier-ignore-end */
