// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bFry1ML5XR1ujHJJdSKVcs
// Component: sbVZc9YGdxY
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_apoiase_website_mobile_first.module.css"; // plasmic-import: bFry1ML5XR1ujHJJdSKVcs/projectcss
import sty from "./PlasmicBrandLogo.module.css"; // plasmic-import: sbVZc9YGdxY/css

import ApoiaseBrandLogoIcon from "./icons/PlasmicIcon__ApoiaseBrandLogo"; // plasmic-import: FLodJSPx7iA/icon

export type PlasmicBrandLogo__VariantMembers = {
  white: "white";
};

export type PlasmicBrandLogo__VariantsArgs = {
  white?: SingleBooleanChoiceArg<"white">;
};

type VariantPropType = keyof PlasmicBrandLogo__VariantsArgs;
export const PlasmicBrandLogo__VariantProps = new Array<VariantPropType>(
  "white"
);

export type PlasmicBrandLogo__ArgsType = {};
type ArgPropType = keyof PlasmicBrandLogo__ArgsType;
export const PlasmicBrandLogo__ArgProps = new Array<ArgPropType>();

export type PlasmicBrandLogo__OverridesType = {
  brandLogo?: p.Flex<"svg">;
};

export interface DefaultBrandLogoProps {
  white?: SingleBooleanChoiceArg<"white">;
  className?: string;
}

export const defaultBrandLogo__Args: Partial<PlasmicBrandLogo__ArgsType> = {};

function PlasmicBrandLogo__RenderFunc(props: {
  variants: PlasmicBrandLogo__VariantsArgs;
  args: PlasmicBrandLogo__ArgsType;
  overrides: PlasmicBrandLogo__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultBrandLogo__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <ApoiaseBrandLogoIcon
      data-plasmic-name={"brandLogo"}
      data-plasmic-override={overrides.brandLogo}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.brandLogo,
        { [sty.brandLogowhite]: hasVariant(variants, "white", "white") }
      )}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  brandLogo: ["brandLogo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  brandLogo: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBrandLogo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBrandLogo__VariantsArgs;
    args?: PlasmicBrandLogo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBrandLogo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBrandLogo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBrandLogo__ArgProps,
      internalVariantPropNames: PlasmicBrandLogo__VariantProps
    });

    return PlasmicBrandLogo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "brandLogo") {
    func.displayName = "PlasmicBrandLogo";
  } else {
    func.displayName = `PlasmicBrandLogo.${nodeName}`;
  }
  return func;
}

export const PlasmicBrandLogo = Object.assign(
  // Top-level PlasmicBrandLogo renders the root element
  makeNodeComponent("brandLogo"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBrandLogo
    internalVariantProps: PlasmicBrandLogo__VariantProps,
    internalArgProps: PlasmicBrandLogo__ArgProps
  }
);

export default PlasmicBrandLogo;
/* prettier-ignore-end */
